language: node_js

node_js:
- 10

before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
  sh -e /etc/init.d/xvfb start; sleep 3; fi

install:
- npm install

script:
- npm run compile
# - npm test

before_deploy:
- npm install -g vsce
- vsce package

deploy:
  provider: releases
  api_key:
    secure: 6MrYyCumSsrIW5CwAJEAaQUDvh0LTY5CLNQh5OShGLCbnW8jth1RK0nE2Lj1JqkCYaMo9S4HoP19/SRYyKxhm0sGdS5t0Ft/+S9n1I0yexMgZZBj0xyz2msbIuquQiZ0AQGaQGr+9U8OrZh7xMWYWFWEFZMMQOJOoMR/KLfbOLrc07OSy/RWW/7w6SEKTYCtGK1K9njHLk9yhUcrzYqgvi8ksUehl7NyjHnYItrs4yCyYv6DYK+vnqjj765HGV2FON4OJHNs2urLLe6AhjEhm4M/YAAOPnPELALP9WhYYmr5n6zVawmMBfIkazmWhN5/My60AtYnKdr0S4SUpzmjJ+Jhb5fn/3InQsdfKPrWh7B/ZcqYU2SRGJmZKD5VihRTO/d8vIb4Nt9MSrYhx4rVfpKsmpaRTLqTkbNE342yViytE9yXhI71BYIP+SM4eQ/TShR0TL1XfoO9FMzeeUks/h0TXgC9GjUKN48QjfoU6I1+kr2kmRJG7pYgA44ZwHrHs+AqCykTQm73qZeYDz6uIU+iRIJ5K1OTwXaXpqM7mDcYhlFH1MEFQHc7NDxAqJP3AkYP+mqSananXVYu9YqopbnVfx43iV/wi7HFssIDQYWt1Sz9r6pAUayaPY3QqOk6/M9FtCrl+r6v9amm9bOXOA4Fa5FOomPllB7mRrgdE/c=
  file_glob: true
  file: "*.vsix"
  skip_cleanup: true
  on:
    repo: julia-vscode/julia-vscode
    tags: true
