trigger:
- master

stages:

- stage: BuildAndTest

  jobs:

  - job: BuildAndTest
    strategy:
      matrix:
        linux:
          imageName: 'ubuntu-latest'
        mac:
          imageName: 'macOS-latest'
        windows:
          imageName: 'windows-latest'

    pool:
      vmImage: $(imageName)

    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '8.x'
      displayName: 'Install Node.js'

    - bash: |
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        echo ">>> Started xvfb"
      displayName: Start xvfb
      condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

    - bash: |
        echo ">>> Compile julia-vscode"
        npm install && npm run compile
        echo ">>> Compiled vscode-test"
        echo ">>> Run sample integration test"
        npm install && npm run compile && npm run test
      displayName: Run Tests
      env:
        DISPLAY: ':99.0'

  - job: PackageRelease
    # condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self
      submodules: true

    - task: NodeTool@0
      inputs:
        versionSpec: '8.x'
      displayName: 'Install Node.js'

    - bash: |
        echo ">>> Package julia-vscode"
        npm install
        npm run package
      displayName: Package

    - task: CopyFiles@2
      inputs:
        Contents: '*.vsix'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'release'
        publishLocation: 'Container'

  - job: PackageInsider
    # condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    pool:
      vmImage: 'windows-latest'

    variables: {description: 'Julia Language Support (Insider)', displayName: 'Julia Insider', name: 'language-julia-insider', version: '0.1.2'}

    steps:
    - checkout: self
      submodules: true

    - task: NodeTool@0
      inputs:
        versionSpec: '8.x'
      displayName: 'Install Node.js'

    - task: FileTransform@2
      inputs:
        folderPath: '$(System.DefaultWorkingDirectory)'
        jsonTargetFiles: 'package.json'      

    - bash: |
        echo ">>> Package julia-vscode"
        npm install
        npm run package
      displayName: Package

    - task: CopyFiles@2
      inputs:
        Contents: '*.vsix'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'insider'
        publishLocation: 'Container'

- stage: Deploy
  jobs:
  - deployment: DeployInsider
    pool:
      vmImage: 'Ubuntu-latest'
    environment: 'Insider'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: insider
          - bash: |
              sudo npm install -g vsce
              PACKAGE_FILENAME=$(find $(Pipeline.Workspace) -type f -name "*.vsix")
              vsce publish -p $MARKET_KEY --packagePath $PACKAGE_FILENAME
            env:
              MARKET_KEY: $(vscekey)
